---
title: "HW_5"
author: "Kalex Robledo"
date: "2025-11-17"
output: pdf_file
---

# Read in homicide dataset
```{r}
#Set working directory to project root
setwd("~/R_Programming/HW_5")
library(ggplot2)
library(dplyr)
library(lubridate)
wp_data <- read.csv("data/homicide-data.csv")
head(wp_data)

```

---

# Clean + Prep Baltimore
```{r}

baltimore <- wp_data %>%
  filter(city == "Baltimore") %>%
  mutate(
    reported_date = as.Date(as.character(reported_date), format = "%Y%m%d"),
    year = year(reported_date),
    month = month(reported_date),
    season = ifelse(month %in% c(5,6,7,8,9,10), "Summer", "Winter")
  )

```

---

# Aggregate monthly counts
```{r}

baltimore_monthly <- baltimore %>%
  mutate(month_date = floor_date(reported_date, "month")) %>%
  group_by(month_date, season) %>%
  summarise(n = n(), .groups = "drop")

# Freddie Gray arrest date
freddie_gray_date <- as.Date("2015-04-12")
```

---

# Bar plot:
```{r}
baltimore_plot <- ggplot(baltimore_monthly, aes(x = month_date, y = n, fill = season)) +
  geom_col(width = 25) +  # bars with fill for legend
  scale_fill_manual(values = c("Summer" = "#969696", "Winter" = "#c7e9fb")) +  # flipped colors
  geom_smooth(aes(group = 1), se = FALSE, color = "blue", size = 1.2,
              method = "loess", span = 0.2) +  # tighter trend line
  geom_vline(xintercept = as.numeric(freddie_gray_date),
             color = "red", linetype = "dashed", size = 1.1) +
  annotate("text",
           x = freddie_gray_date + 120,
           y = max(baltimore_monthly$n) * 0.95,
           label = "Arrest of\nFreddie Gray",
           color = "gray30",
           hjust = 0,
           size = 4) +
  labs(
 title = "Homicides in Baltimore, MD",
    x = "Date",
    y = "Monthly Homicides",
    fill = "Season"  # legend title
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",         # move legend below x-axis
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 11),
    plot.margin = margin(20, 20, 20, 20)
  )
```

---

# Save the figure
```{r}
ggsave("../figures/baltimore_monthly_homicides.png",
       baltimore_plot, width = 10, height = 4.5)

baltimore_plot

```

---

#install LaTeX 
```{r}
tinytex::install_tinytex()
```




